spring:
    application:
        name: backend-base
    datasource:
        url: jdbc:postgresql://localhost:54620/mikrum-demo
        username: postgres
        password: postgres123
        driver-class-name: org.postgresql.Driver
    liquibase:
        change-log: classpath:db/changelog/master.xml
        enabled: true
        contexts: TEST
logging:
    level:
        org.springframework.security: TRACE